### ISSUE TITLE
Debug: can't delete 'watch' tab variables

### ISSUE THREAD

**Issue by ma-michelle** [cee-studio/IDE#10]
Steps to reproduce:
1. demo: https://cee.studio/?bucket=200727-X49&name=priority-queue
2. set breakpoint to line 61
3. debug > start > step into until variable 'j' appears under auto tab
4. add variable 'j' under watch tab
5. click on variable 'j''s name, backspace to get rid of the name, and either press enter or click outside of the text field (although enter doesn't properly exit the text field)

![image](https://user-images.githubusercontent.com/56993432/88628221-70704600-d062-11ea-9471-ff08f2e29503.png)

6. if you keep pressing step into until the value of variable 'j' is changed again in the code, 'j' reappears under the watch tab

![image](https://user-images.githubusercontent.com/56993432/88628258-7fef8f00-d062-11ea-8a07-fa3c8d916219.png)

Pressing the delete button doesn't seem to work either.

**Comment by xzhang1863** [comment]
The fix has been merged into master branch

**Comment by xzhang1863** [comment]
This issue should have been fixed, please verify.
