### ISSUE TITLE
Debug: '\n' shows up in help descriptions

### ISSUE THREAD

**Issue by ma-michelle** [cee-studio/IDE#13]
1. demo: https://cee.studio/?bucket=200730-Zz4&name=priority-queue.LgVM
2. click on debug > GDB console
3. type `help b`

![image](https://user-images.githubusercontent.com/56993432/88900862-e1e7fa00-d204-11ea-820f-6b97243d513d.png)

**Comment by xzhang1863** [comment]
The fix has been submitted into x11 branch.

**Comment by mlite** [comment]
this is fixed.
