### ISSUE TITLE
Wrong error message for `strcpy("foo", str)`

### ISSUE THREAD

**Issue by Jorengarenar** [cee-studio/IDE#2]
For sample code:
```c
#include <stdio.h>
#include <string.h>

int main()
{
    char str[10];
    strcpy("foo", str);
    return 0;
}
```
The error message is: `reading from the outside of a memory block`

When correct message is: `clobbering immutable memory block`

[Screenshot](https://imgur.com/a/RsBAtSl)

**Comment by mlite** [comment]
This is a bug, it's fixed and released to the production.
