### ISSUE TITLE
Project settings dropdown menu goes off-screen

### ISSUE THREAD

**Issue by ma-michelle** [cee-studio/IDE#7]
When you have many projects and click the three-dots menu, the context menu goes off-screen so that you can't click on the 'Clone' or 'Share' buttons.

![image](https://user-images.githubusercontent.com/56993432/88449519-72d16680-cdfc-11ea-9003-b941c5972f8e.png)

**Comment by mlite** [comment]
Yes, we will fix this.  Thanks for reporting it.

**Comment by mlite** [comment]
This should be fixed in the next release.

**Comment by mlite** [comment]
Can you please verify if this is fixed in the staging site?

**Comment by ma-michelle** [comment]
> Can you please verify if this is fixed in the staging site?

I tested it just now with this https://cde.stensal.io/?bucket=2020-cs50 and everything looks good!

![image](https://user-images.githubusercontent.com/56993432/89234646-45757d00-d5a1-11ea-9b49-41facb0c3207.png)

**Comment by stensalweb** [comment]
You can close the issue once you verified.  If it's still a bug, it is counted as a new bug.
